-- MySQL Script generated by MySQL Workbench
-- 10/25/16 20:20:07
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema e_library
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `e_library` ;

-- -----------------------------------------------------
-- Schema e_library
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `e_library` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `e_library` ;

-- -----------------------------------------------------
-- Table `book`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `book` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `book` (
  `id` INT NOT NULL,
  `author` VARCHAR(50) NULL,
  `book_name` VARCHAR(50) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
